/**
 * @lumen/codegen — target 'webcomponent': self-contained custom element.
 *
 * Emits a `<lumen-embed>` element wrapping the engine in a shadow DOM. The
 * SceneIR ships embedded as a default; the `config-url` attribute (or
 * `config` property) overrides it at mount time.
 */

import type { CodegenResult, GeneratedModule } from '@lumen/contracts';
import { SourceFileBuilder } from './emit.js';
import {
  RUNTIME_SPECIFIER,
  ann,
  criticalCss,
  finalizeModule,
  irDeclaration,
  moduleExt,
  type TargetContext,
} from './common.js';

/** Generate the custom element module for the webcomponent target. */
export function renderWebComponent(ctx: TargetContext): GeneratedModule {
  const ext = moduleExt(ctx.options);
  const b = new SourceFileBuilder(`lumen-embed${ext}`);
  b.bannerLine('Generated by @lumen/codegen (target: webcomponent). Do not edit.');
  if (ctx.options.banner) b.bannerLine(ctx.options.banner);
  b.imports.add(RUNTIME_SPECIFIER, 'bootEngine');
  const w = b.writer;
  w.line(irDeclaration(ctx));
  w.line();
  w.line(`const CRITICAL_CSS = ${JSON.stringify(criticalCss(ctx.ir.theme))};`);
  w.line();
  w.line('/**');
  w.line(' * <lumen-embed> — self-contained Lumen engine custom element.');
  w.line(' * Attributes:');
  w.line(' *   config-url  — fetch a SceneIR JSON document from this URL instead of the embedded one.');
  w.line(' */');
  w.block('export class LumenEmbed extends HTMLElement', (bw) => {
    bw.block(`static get observedAttributes()${ann(ctx, ': string[]')}`, (aw) => {
      aw.line("return ['config-url'];");
    });
    bw.line();
    bw.line(`engine${ann(ctx, ': unknown')} = null;`);
    bw.line(`shadow${ann(ctx, ': ShadowRoot')};`);
    bw.line();
    bw.block('constructor()', (cw) => {
      cw.line('super();');
      cw.line("this.shadow = this.attachShadow({ mode: 'open' });");
    });
    bw.line();
    bw.block(`async connectedCallback()${ann(ctx, ': Promise<void>')}`, (cw) => {
      cw.line('const style = document.createElement(\'style\');');
      cw.line('style.textContent = CRITICAL_CSS;');
      cw.line('const host = document.createElement(\'main\');');
      cw.line("host.className = 'lumen-root';");
      cw.line('this.shadow.append(style, host);');
      cw.line('const ir = await this.resolveIR();');
      cw.line('this.engine = await bootEngine(host, ir);');
    });
    bw.line();
    bw.block(`disconnectedCallback()${ann(ctx, ': void')}`, (cw) => {
      cw.line(`const disposable = this.engine${ann(ctx, ' as { dispose?: () => void } | null')};`);
      cw.line('disposable?.dispose?.();');
      cw.line('this.engine = null;');
    });
    bw.line();
    bw.block(`attributeChangedCallback(name${ann(ctx, ': string')})${ann(ctx, ': void')}`, (cw) => {
      cw.block("if (name === 'config-url' && this.isConnected)", (iw) => {
        iw.block('void this.resolveIR().then(async (ir) =>', (pw) => {
          pw.line("const host = this.shadow.querySelector('main');");
          pw.line(`if (host) this.engine = await bootEngine(host${ann(ctx, ' as HTMLElement')}, ir);`);
        }, '});');
      });
    });
    bw.line();
    bw.block(`async resolveIR()${ann(ctx, ': Promise<typeof SCENE_IR>')}`, (cw) => {
      cw.line("const url = this.getAttribute('config-url');");
      cw.line('if (!url) return SCENE_IR;');
      cw.line('const res = await fetch(url);');
      cw.line('if (!res.ok) throw new Error(`lumen-embed: failed to fetch config ${url}: ${res.status}`);');
      cw.line(`return (await res.json())${ann(ctx, ' as typeof SCENE_IR')};`);
    });
  });
  w.line();
  w.block("if (!customElements.get('lumen-embed'))", (bw) => {
    bw.line("customElements.define('lumen-embed', LumenEmbed);");
  });
  return finalizeModule(b.build(), ctx.options);
}

/** Run the 'webcomponent' target. */
export function generateWebComponent(
  ctx: TargetContext,
): Pick<CodegenResult, 'entry' | 'files' | 'ssrHtml' | 'hydrationManifest'> {
  const mod = renderWebComponent(ctx);
  return {
    entry: mod.path,
    files: [mod],
    ssrHtml: '',
    hydrationManifest: {
      islands: ctx.ir.hydration.islands.map((id) => ({
        id,
        module: mod.path,
        trigger: 'eager' as const,
        props: { sceneId: id, host: 'shadow-dom' },
      })),
    },
  };
}
