/**
 * tests/saas-smoke — (c) asset enqueue (mock executor) → manifest generated
 * → AssetLibrary.
 *
 * The real @lumen/app-assets AssetUploadQueue runs a mock executor (the
 * package's own pluggable executor seam — no ffmpeg, no network), the real
 * HybridManifestGenerator emits the hybrid manifest, and the real
 * AssetLibrary stores it. The offline backend facade's own asset queue slot
 * (in-memory, hosted-shaped rows) is asserted too.
 */
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { createOfflineBackend } from '@lumen/backend-supabase';
import {
  AssetLibrary,
  AssetUploadQueue,
  HybridManifestGenerator,
} from '@lumen/app-assets';

test('(c) upload queue (mock executor) → hybrid manifest → AssetLibrary', async () => {
  const calls = [];
  const executor = {
    async execute(job, op) {
      calls.push(`${job.id}:${op}`);
      return { op, ok: true };
    },
  };
  const queue = new AssetUploadQueue({ executor });
  const events = [];
  queue.onProgress((p) => events.push(p));

  queue.enqueue({
    id: 'hero',
    kind: 'video',
    sourceName: 'hero.mp4',
    bytes: new Uint8Array([1, 2, 3, 4]),
    ops: ['probe', 'scrub-mp4', 'manifest'],
  });
  await queue.idle();

  assert.deepEqual(calls, ['hero:probe', 'hero:scrub-mp4', 'hero:manifest']);
  const [rec] = queue.listJobs();
  assert.equal(rec.state, 'done');
  assert.equal(rec.results.length, 3);
  assert.equal(events.at(-1).state, 'done');

  // Manifest generated by the real HybridManifestGenerator.
  const manifest = new HybridManifestGenerator().generate({
    name: 'hero',
    scrubBytes: new Uint8Array([1, 2, 3, 4]),
  });
  assert.ok(manifest, 'manifest generated');

  // Stored in the real AssetLibrary (in-memory, no storage adapter).
  const library = new AssetLibrary();
  const record = library.put({
    assetId: 'hero',
    name: 'hero',
    manifest,
    deviceProfiles: ['desktop'],
  });
  assert.ok(record.createdAt.endsWith('Z'));
  assert.equal(library.size, 1);
  assert.equal(library.get('hero').name, 'hero');
  assert.deepEqual(library.get('hero').deviceProfiles, ['desktop']);
  assert.deepEqual(library.list().map((r) => r.assetId), ['hero']);
});

test('(c) offline backend asset queue slot mirrors hosted shapes', async () => {
  const backend = createOfflineBackend();
  const { asset, job } = await backend.assets.enqueue({
    projectId: 'p1',
    name: 'cover.png',
    kind: 'image',
    ops: ['optimize'],
  });
  assert.equal(asset.projectId, 'p1');
  assert.equal(asset.status, 'done');
  assert.equal(job.assetId, asset.id);
  assert.equal(job.progress, 100);
  assert.deepEqual((await backend.assets.listAssets('p1')).map((a) => a.id), [asset.id]);
  assert.deepEqual(await backend.assets.getAsset(asset.id), asset);
});
