/**
 * @lumen/codegen — target 'runtime': minimal JSON loader.
 *
 * Emits a tiny loader module that fetches a SceneIR/config JSON document by
 * URL (script tag `data-config-url` attribute or explicit argument) and boots
 * the engine. Nothing is embedded — the heaviest variant is loaded lazily.
 */

import type { CodegenResult, GeneratedModule } from '@lumen/contracts';
import { SourceFileBuilder } from './emit.js';
import {
  RUNTIME_SPECIFIER,
  ann,
  finalizeModule,
  moduleExt,
  type TargetContext,
} from './common.js';

/** Generate the runtime loader entry module. */
export function renderRuntimeLoader(ctx: TargetContext): GeneratedModule {
  const ext = moduleExt(ctx.options);
  const b = new SourceFileBuilder(`loader${ext}`);
  b.bannerLine('Generated by @lumen/codegen (target: runtime). Do not edit.');
  if (ctx.options.banner) b.bannerLine(ctx.options.banner);
  b.imports.add(RUNTIME_SPECIFIER, 'bootEngine');
  const w = b.writer;
  w.line('/** Minimal Lumen runtime loader: fetch SceneIR JSON by URL, boot engine. */');
  w.block(
    `export async function loadLumen(configUrl${ann(ctx, ': string')}, root${ann(
      ctx,
      '?: HTMLElement',
    )})${ann(ctx, ': Promise<unknown>')}`,
    (bw) => {
      bw.line('const res = await fetch(configUrl, { credentials: \'same-origin\' });');
      bw.line('if (!res.ok) throw new Error(`lumen loader: failed to fetch ${configUrl}: ${res.status}`);');
      bw.line('const ir = await res.json();');
      bw.line('const host =');
      bw.indent();
      bw.line('root ??');
      bw.line("document.getElementById('lumen-root') ??");
      bw.line("document.body.appendChild(Object.assign(document.createElement('main'), { id: 'lumen-root' }));");
      bw.dedent();
      bw.line('return bootEngine(host, ir);');
    },
  );
  w.line();
  w.line('// Auto-boot when loaded via <script data-config-url="...">.');
  w.line("const selfScript = typeof document !== 'undefined' ? document.currentScript : null;");
  w.line("const autoUrl = selfScript?.getAttribute('data-config-url');");
  w.block('if (autoUrl)', (bw) => {
    bw.line('// Surface boot failures: console + visible fallback + DOM event.');
    bw.line(`void loadLumen(autoUrl).catch((err) => {`);
    bw.indent();
    bw.line("console.error('[lumen] boot failed', err);");
    bw.line("const host = document.getElementById('lumen-root');");
    bw.line('if (host) {');
    bw.indent();
    bw.line(`host.innerHTML = '<p role="alert" class="lumen-boot-error">This experience failed to load. Please reload the page.</p>';`);
    bw.dedent();
    bw.line('}');
    bw.line("window.dispatchEvent(new CustomEvent('lumen:boot-error', { detail: err }));");
    bw.dedent();
    bw.line('});');
  });
  return finalizeModule(b.build(), ctx.options);
}

/** Run the 'runtime' target. */
export function generateRuntime(
  ctx: TargetContext,
): Pick<CodegenResult, 'entry' | 'files' | 'ssrHtml' | 'hydrationManifest'> {
  const mod = renderRuntimeLoader(ctx);
  return {
    entry: mod.path,
    files: [mod],
    ssrHtml: '',
    hydrationManifest: { islands: [] },
  };
}
