/**
 * BrowserMediaExecutor — a real in-browser AssetJobExecutor for the
 * @lumen/app-assets upload queue.
 *
 * The production CliExecutor shells out to the lumen-media CLI (Node-only),
 * so in the browser this executor performs what the platform genuinely can:
 *
 *   - probe:        real metadata via createImageBitmap / HTMLVideoElement
 *                   (dimensions, duration).
 *   - scrub-mp4:    pass-through of the source bytes — the browser cannot
 *                   re-encode GOP-1 scrub MP4s; the output record says so.
 *   - frame-stack:  for images, a single "frame" (the source bytes); for
 *                   video this needs ffmpeg, so it throws
 *                   FfmpegUnavailableError — the real error type the hosted
 *                   pipeline raises, surfaced in the UI with guidance.
 *   - poster:       images pass through; video poster extraction would need
 *                   ffmpeg (reported as FfmpegUnavailableError).
 *   - manifest:     marker op — the UI runs HybridManifestGenerator over the
 *                   collected op outputs when the job completes.
 *
 * No fake network, no fake processing: every byte handed back is the real
 * source byte stream, and unsupported operations fail with the pipeline's
 * own error type.
 */

import {
  FfmpegUnavailableError,
  type AssetJobExecutor,
  type AssetJobInput,
  type AssetOp,
  type AssetOpContext,
  type AssetOpResult,
} from '@lumen/app-assets';

const FFMPEG_GUIDANCE =
  'Re-encoding video in the browser is not available. Run the hosted pipeline: ' +
  '`node app/cli/dist/index.js media <file>` (requires ffmpeg) — or upload an image.';

async function probeImage(bytes: Uint8Array): Promise<Record<string, unknown>> {
  const blob = new Blob([bytes.buffer as ArrayBuffer]);
  const bitmap = await createImageBitmap(blob);
  const out = { width: bitmap.width, height: bitmap.height };
  bitmap.close();
  return out;
}

function probeVideo(bytes: Uint8Array): Promise<Record<string, unknown>> {
  return new Promise((resolve, reject) => {
    const url = URL.createObjectURL(new Blob([bytes.buffer as ArrayBuffer]));
    const video = document.createElement('video');
    video.preload = 'metadata';
    video.muted = true;
    const done = (fn: () => void) => {
      URL.revokeObjectURL(url);
      fn();
    };
    video.onloadedmetadata = () =>
      done(() =>
        resolve({
          width: video.videoWidth,
          height: video.videoHeight,
          duration: video.duration,
        }),
      );
    video.onerror = () =>
      done(() => reject(new Error('The browser could not decode this video file.')));
    video.src = url;
  });
}

export class BrowserMediaExecutor implements AssetJobExecutor {
  async execute(
    job: AssetJobInput,
    op: AssetOp,
    _ctx: AssetOpContext,
  ): Promise<AssetOpResult> {
    switch (op) {
      case 'probe': {
        const meta = job.kind === 'image' ? await probeImage(job.bytes) : await probeVideo(job.bytes);
        return { op, ok: true, outputs: { probe: meta } };
      }
      case 'scrub-mp4': {
        if (job.kind !== 'video') {
          return { op, ok: true, outputs: { note: 'scrub-mp4 not applicable to images' } };
        }
        return {
          op,
          ok: true,
          outputs: {
            scrubBytes: job.bytes,
            note: 'pass-through (browser build); the hosted pipeline emits a GOP-1 scrub MP4',
          },
        };
      }
      case 'frame-stack': {
        if (job.kind !== 'video') {
          return {
            op,
            ok: true,
            outputs: { frameStacks: [{ fps: 1, frameCount: 1, bytes: job.bytes }] },
          };
        }
        throw new FfmpegUnavailableError('ffmpeg', FFMPEG_GUIDANCE);
      }
      case 'manifest': {
        return { op, ok: true, outputs: { note: 'manifest generated by the Builder UI' } };
      }
      default:
        return { op, ok: false, error: `unsupported op: ${op}` };
    }
  }
}
