/**
 * @lumen/codegen — target 'npm': ESM library entry.
 *
 * Emits a package entry module that re-exports the runtime factory plus a
 * preconfigured `createEngine` variant with the SceneIR baked in, so library
 * consumers get a zero-config engine for this site.
 */

import type { CodegenResult, GeneratedModule } from '@lumen/contracts';
import { SourceFileBuilder, safeIdentifier } from './emit.js';
import {
  RUNTIME_SPECIFIER,
  ann,
  finalizeModule,
  irDeclaration,
  moduleExt,
  type TargetContext,
} from './common.js';

/** Generate the npm library entry module. */
export function renderNpmEntry(ctx: TargetContext): GeneratedModule {
  const ext = moduleExt(ctx.options);
  const b = new SourceFileBuilder(`index${ext}`);
  b.bannerLine('Generated by @lumen/codegen (target: npm). Do not edit.');
  if (ctx.options.banner) b.bannerLine(ctx.options.banner);
  b.imports.add(RUNTIME_SPECIFIER, 'bootEngine', 'hydrateIslands');
  const w = b.writer;
  w.line(irDeclaration(ctx));
  w.line();
  const factory = safeIdentifier(`create_${ctx.config.id}_engine`);
  w.line('/** SceneIR for this site, embedded at build time. */');
  w.line('export const sceneIR = SCENE_IR;');
  w.line();
  w.line('/** Preconfigured engine factory: boots this site\'s scene with zero config. */');
  w.block(
    `export async function ${factory}(root${ann(ctx, ': HTMLElement')})${ann(ctx, ': Promise<unknown>')}`,
    (bw) => {
      bw.line('const engine = await bootEngine(root, SCENE_IR);');
      bw.line('await hydrateIslands(engine, SCENE_IR.hydration.islands);');
      bw.line('return engine;');
    },
  );
  w.line();
  w.line('// Re-export the raw runtime API for advanced consumers.');
  w.line(`export { bootEngine, hydrateIslands } from '${RUNTIME_SPECIFIER}';`);
  return finalizeModule(b.build(), ctx.options);
}

/** Run the 'npm' target. */
export function generateNpm(
  ctx: TargetContext,
): Pick<CodegenResult, 'entry' | 'files' | 'ssrHtml' | 'hydrationManifest'> {
  const mod = renderNpmEntry(ctx);
  return {
    entry: mod.path,
    files: [mod],
    ssrHtml: '',
    hydrationManifest: {
      islands: ctx.ir.hydration.islands.map((id) => ({
        id,
        module: mod.path,
        trigger: 'visible' as const,
        props: { sceneId: id },
      })),
    },
  };
}
