/**
 * @lumen/codegen — target 'static': static site generation.
 *
 * Emits a semantic index.html (SEO meta, inline critical CSS from theme
 * tokens, SSR skeleton of the first scene, noscript fallback) plus a main
 * module that embeds the SceneIR JSON and boots @lumen/runtime.
 */

import type { CodegenResult, GeneratedModule, HydrationManifest } from '@lumen/contracts';
import { CodeWriter, SourceFileBuilder, escapeHtml } from './emit.js';
import {
  RUNTIME_SPECIFIER,
  ann,
  criticalCss,
  finalizeModule,
  irDeclaration,
  irScriptTag,
  minifyHtml,
  moduleExt,
  ssrSkeleton,
  importMapScript,
  type TargetContext,
} from './common.js';

/** Per-scene semantic wrapper for the SSR body. */
function sceneSections(ctx: TargetContext, w: CodeWriter): void {
  const { config, ir } = ctx;
  const ssr = ctx.options.target.ssr !== false && ir.hydration.ssr;
  for (let i = 0; i < config.scenes.length; i++) {
    const sc = config.scenes[i];
    const island = ir.hydration.islands.includes(sc.id);
    const attrs = [
      `id="${escapeHtml(sc.id)}"`,
      'class="lumen-scene"',
      `data-slot="${escapeHtml(sc.slot)}"`,
      `aria-label="${escapeHtml(sc.a11y.label)}"`,
    ];
    if (island) attrs.push('data-lumen-island="true"');
    w.line(`<section ${attrs.join(' ')}>`);
    w.indent();
    if (ssr && i === 0) {
      w.line(ssrSkeleton(ir, config));
    } else if (sc.a11y.summary) {
      w.line(`<p class="lumen-visually-hidden">${escapeHtml(sc.a11y.summary)}</p>`);
    }
    w.dedent();
    w.line('</section>');
  }
}

/** Generate the index.html document for the static target. */
export function renderStaticHtml(ctx: TargetContext, entryPath: string): string {
  const { config, ir } = ctx;
  const meta = config.meta;
  const w = new CodeWriter();
  w.line('<!doctype html>');
  w.line(`<html lang="${escapeHtml(meta.locale)}">`);
  w.line('<head>');
  w.indent();
  w.line('<meta charset="utf-8">');
  w.line('<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">');
  w.line(`<title>${escapeHtml(meta.title)}</title>`);
  w.line(`<meta name="description" content="${escapeHtml(meta.description)}">`);
  w.line(`<meta property="og:title" content="${escapeHtml(meta.title)}">`);
  w.line(`<meta property="og:description" content="${escapeHtml(meta.description)}">`);
  w.line('<meta property="og:type" content="website">');
  if (meta.ogImage) {
    w.line(`<meta property="og:image" content="${escapeHtml(meta.ogImage)}">`);
  }
  w.line(importMapScript());
  w.line('<style>');
  w.indent();
  w.line(criticalCss(ir.theme));
  w.dedent();
  w.line('</style>');
  w.dedent();
  w.line('</head>');
  w.line('<body>');
  w.indent();
  w.line(`<main class="lumen-root" id="lumen-root" data-site="${escapeHtml(config.id)}">`);
  w.indent();
  sceneSections(ctx, w);
  w.dedent();
  w.line('</main>');
  w.line('<noscript>');
  w.indent();
  w.line('<div class="lumen-noscript">');
  w.indent();
  w.line(`<h1>${escapeHtml(meta.title)}</h1>`);
  w.line(`<p>${escapeHtml(meta.description)}</p>`);
  for (const sc of config.scenes) {
    w.line(`<section aria-label="${escapeHtml(sc.a11y.label)}">`);
    w.indent();
    if (sc.a11y.summary) w.line(`<p>${escapeHtml(sc.a11y.summary)}</p>`);
    w.dedent();
    w.line('</section>');
  }
  w.dedent();
  w.line('</div>');
  w.dedent();
  w.line('</noscript>');
  w.line(irScriptTag(ctx, 'lumen-scene-ir'));
  w.line(`<script type="module" src="./${escapeHtml(entryPath)}"></script>`);
  w.dedent();
  w.line('</body>');
  w.line('</html>');
  return minifyHtml(w.toString(), ctx.options);
}

/** Generate the main entry module for the static target. */
export function renderStaticEntry(ctx: TargetContext): GeneratedModule {
  const ext = moduleExt(ctx.options);
  const b = new SourceFileBuilder(`main${ext}`);
  b.bannerLine('Generated by @lumen/codegen (target: static). Do not edit.');
  if (ctx.options.banner) b.bannerLine(ctx.options.banner);
  b.imports.add(RUNTIME_SPECIFIER, 'bootEngine', 'hydrateIslands');
  const w = b.writer;
  w.line(irDeclaration(ctx));
  w.line();
  w.line("const irTag = document.getElementById('lumen-scene-ir');");
  w.line('const ir = irTag ? JSON.parse(irTag.textContent ?? \'null\') ?? SCENE_IR : SCENE_IR;');
  w.line();
  w.block(`async function main()${ann(ctx, ': Promise<void>')}`, (bw) => {
    bw.line("const root = document.getElementById('lumen-root');");
    bw.line("if (!root) throw new Error('lumen root element missing');");
    bw.line('const engine = await bootEngine(root, ir);');
    bw.line("engine.on('engine:error', (err) => {");
    bw.indent();
    bw.line("console.error('[lumen] engine:error', err);");
    bw.line("window.dispatchEvent(new CustomEvent('lumen:engine-error', { detail: err }));");
    bw.dedent();
    bw.line('});');
    bw.line('await hydrateIslands(engine, ir.hydration.islands);');
  });
  w.line();
  w.line('// Boot failures must never be silent: log, surface a visible fallback,');
  w.line('// and notify host pages via a DOM event.');
  w.block(`function reportBootError(err${ann(ctx, ': unknown')})${ann(ctx, ': void')}`, (bw) => {
    bw.line("console.error('[lumen] boot failed', err);");
    bw.line("const root = document.getElementById('lumen-root');");
    bw.line('if (root) {');
    bw.indent();
    bw.line(`root.innerHTML = '<p role="alert" class="lumen-boot-error">This experience failed to load. Please reload the page.</p>';`);
    bw.dedent();
    bw.line('}');
    bw.line("window.dispatchEvent(new CustomEvent('lumen:boot-error', { detail: err }));");
  });
  w.line();
  w.line('void main().catch(reportBootError);');
  return finalizeModule(b.build(), ctx.options);
}

/** Run the 'static' target. Returns partial CodegenResult fields. */
export function generateStatic(ctx: TargetContext): Pick<CodegenResult, 'entry' | 'files' | 'ssrHtml' | 'hydrationManifest'> {
  const entryMod = renderStaticEntry(ctx);
  const html = renderStaticHtml(ctx, entryMod.path);
  const htmlMod: GeneratedModule = { path: 'index.html', source: html, imports: [] };
  const islands: HydrationManifest['islands'] = ctx.ir.hydration.islands.map((id) => ({
    id,
    module: entryMod.path,
    trigger: id === ctx.config.scenes[0]?.id ? ('eager' as const) : ('visible' as const),
    props: { sceneId: id },
  }));
  return {
    entry: entryMod.path,
    files: [entryMod, htmlMod],
    ssrHtml: ctx.options.target.ssr === false ? '' : html,
    hydrationManifest: { islands },
  };
}
