/**
 * @lumen/codegen — orchestrating entry: `generate()`.
 *
 * Lowers config + composed scene into a SceneIR, collects warnings, and
 * dispatches to the per-target generator selected by `options.target.target`.
 */

import type {
  AssetManifest,
  CodegenOptions,
  CodegenResult,
  CodegenWarning,
  ComposedScene,
  EngineConfig,
  GeneratedModule,
  TemplateDescriptor,
} from '@lumen/contracts';
import { SCENE_IR_VERSION } from '@lumen/contracts';
import {
  collectA11yWarnings,
  collectAssetWarnings,
  prepareIRJson,
  type TargetContext,
} from './common.js';
import { lowerToIR } from './ir.js';
import { generateStatic } from './gen-static.js';
import { generateWebComponent } from './gen-webcomponent.js';
import { generateRuntime } from './gen-runtime.js';
import { generateNpm } from './gen-npm.js';

/** Type declaration bundle for the emitted entry API. */
function typeDeclarations(ctx: TargetContext, entry: string): string {
  const lines = [
    '// Generated by @lumen/codegen — public API surface of the emitted bundle.',
    `declare module '${entry.replace(/\.(ts|js)$/, '')}' {`,
  ];
  switch (ctx.options.target.target) {
    case 'static':
      lines.push('  /** Boots the engine against the SSR shell. (side-effect entry) */');
      lines.push('  export {};');
      break;
    case 'webcomponent':
      lines.push('  /** <lumen-embed> custom element class. */');
      lines.push('  export class LumenEmbed extends HTMLElement {}');
      break;
    case 'npm':
      lines.push('  /** Embedded SceneIR for this site. */');
      lines.push('  export const sceneIR: unknown;');
      lines.push('  /** Boot the engine with the embedded config. */');
      lines.push('  export function bootEngine(root: HTMLElement, ir: unknown): Promise<unknown>;');
      lines.push('  export function hydrateIslands(engine: unknown, islands: string[]): Promise<void>;');
      break;
    case 'runtime':
      lines.push('  /** Fetch config JSON by URL and boot the engine. */');
      lines.push('  export function loadLumen(configUrl: string, root?: HTMLElement): Promise<unknown>;');
      break;
  }
  lines.push('}', '');
  return lines.join('\n');
}

/**
 * Generate code for the given target.
 *
 * @param config    Validated EngineConfig (from @lumen/config).
 * @param descriptor TemplateDescriptor for config.template (from @lumen/templates);
 *                   supplies default theme tokens and capability requirements.
 * @param scene     ComposedScene produced by `descriptor.compose(config, manifest)`.
 * @param options   Codegen options, including the target descriptor.
 */
export function generate(
  config: EngineConfig,
  descriptor: TemplateDescriptor,
  scene: ComposedScene,
  options: CodegenOptions,
  manifest?: AssetManifest,
): CodegenResult {
  const warnings: CodegenWarning[] = [];
  const ir = lowerToIR(config, descriptor.themeTokens, scene);
  warnings.push(...collectAssetWarnings(config, ir));
  warnings.push(...collectA11yWarnings(config, ir));
  const { json, warnings: jsonWarnings } = prepareIRJson(config, ir);
  warnings.push(...jsonWarnings);

  const ctx: TargetContext = {
    config,
    ir,
    irJson: json,
    options,
    requiredCapabilities: {
      renderers: [...descriptor.requiredCapabilities.renderers],
      assetFeatures: [...descriptor.requiredCapabilities.assetFeatures],
      interactions: [...descriptor.requiredCapabilities.interactions],
    },
    warnings,
    ...(manifest ? { manifest } : {}),
  };

  let out: Pick<CodegenResult, 'entry' | 'files' | 'ssrHtml' | 'hydrationManifest'>;
  switch (options.target.target) {
    case 'static':
      out = generateStatic(ctx);
      break;
    case 'webcomponent':
      out = generateWebComponent(ctx);
      break;
    case 'runtime':
      out = generateRuntime(ctx);
      break;
    case 'npm':
      out = generateNpm(ctx);
      break;
    default: {
      const never: never = options.target.target;
      throw new Error(`Unknown codegen target: ${String(never)}`);
    }
  }

  // Append the hydration manifest as a JSON file when islands exist. The
  // manifest is stamped with the SceneIR schema version it was lowered from.
  const hydrationManifest: CodegenResult['hydrationManifest'] = {
    irVersion: SCENE_IR_VERSION,
    ...out.hydrationManifest,
  };
  const files: GeneratedModule[] = [...out.files];
  if (hydrationManifest.islands.length > 0) {
    files.push({
      path: 'hydration-manifest.json',
      source: JSON.stringify(hydrationManifest, null, 2) + '\n',
      imports: [],
    });
  }

  const importGraph = [...new Set(files.flatMap((f) => f.imports))].sort();

  return {
    entry: out.entry,
    files,
    hydrationManifest,
    typeDeclarations: typeDeclarations(ctx, out.entry),
    ssrHtml: out.ssrHtml,
    importGraph,
    warnings,
  };
}
