/**
 * @lumen/codegen — target 'webcomponent': self-contained custom element.
 *
 * Emits a `<lumen-embed>` element wrapping the engine in a shadow DOM. The
 * SceneIR ships embedded as a default; the `config-url` attribute (or
 * `config` property) overrides it at mount time.
 */

import type { CodegenResult, GeneratedModule } from '@lumen/contracts';
import { SourceFileBuilder } from './emit.js';
import {
  RUNTIME_SPECIFIER,
  ann,
  criticalCss,
  finalizeModule,
  irDeclaration,
  moduleExt,
  type TargetContext,
} from './common.js';

/** Generate the custom element module for the webcomponent target. */
export function renderWebComponent(ctx: TargetContext): GeneratedModule {
  const ext = moduleExt(ctx.options);
  const b = new SourceFileBuilder(`lumen-embed${ext}`);
  b.bannerLine('Generated by @lumen/codegen (target: webcomponent). Do not edit.');
  if (ctx.options.banner) b.bannerLine(ctx.options.banner);
  b.imports.add(RUNTIME_SPECIFIER, 'bootEngine');
  const w = b.writer;
  w.line(irDeclaration(ctx));
  w.line();
  w.line(`const CRITICAL_CSS = ${JSON.stringify(criticalCss(ctx.ir.theme))};`);
  w.line();
  w.line('/**');
  w.line(' * <lumen-embed> — self-contained Lumen engine custom element.');
  w.line(' * Attributes:');
  w.line(' *   config-url  — fetch a SceneIR JSON document from this URL instead of the embedded one.');
  w.line(' */');
  w.block('export class LumenEmbed extends HTMLElement', (bw) => {
    bw.block(`static get observedAttributes()${ann(ctx, ': string[]')}`, (aw) => {
      aw.line("return ['config-url'];");
    });
    bw.line();
    bw.line(`engine${ann(ctx, ': { dispose?: () => Promise<void> | void } | null')} = null;`);
    bw.line(`shadow${ann(ctx, ': ShadowRoot')};`);
    bw.line('/** Boot generation token: stale boots (disconnect/attr change mid-boot) are dropped. */');
    bw.line(`bootGen${ann(ctx, ': number')} = 0;`);
    bw.line();
    bw.block('constructor()', (cw) => {
      cw.line('super();');
      cw.line("this.shadow = this.attachShadow({ mode: 'open' });");
    });
    bw.line();
    bw.block(`connectedCallback()${ann(ctx, ': void')}`, (cw) => {
      cw.block("if (!this.shadow.querySelector('main'))", (iw) => {
        iw.line('const style = document.createElement(\'style\');');
        iw.line('style.textContent = CRITICAL_CSS;');
        iw.line('const host = document.createElement(\'main\');');
        iw.line("host.className = 'lumen-root';");
        iw.line('this.shadow.append(style, host);');
      });
      cw.line('void this.boot();');
    });
    bw.line();
    bw.line('/** (Re)boot the engine. Disposes any previous engine first; a stale');
    bw.line(' * generation (disconnect or newer boot) abandons its result. */');
    bw.block(`async boot()${ann(ctx, ': Promise<void>')}`, (cw) => {
      cw.line('const gen = ++this.bootGen;');
      cw.block('try', (tw) => {
        tw.line('const ir = await this.resolveIR();');
        tw.line('if (gen !== this.bootGen || !this.isConnected) return;');
        tw.line('const previous = this.engine;');
        tw.line('this.engine = null;');
        tw.line('await previous?.dispose?.();');
        tw.line("const host = this.shadow.querySelector('main');");
        tw.line('if (!host) return;');
        tw.line(`this.engine = await bootEngine(host${ann(ctx, ' as HTMLElement')}, ir);`);
      });
      cw.block(`catch (err)`, (ew) => {
        ew.line("console.error('[lumen] lumen-embed boot failed', err);");
        ew.line("const host = this.shadow.querySelector('main');");
        ew.line(`if (host) host.innerHTML = '<p role="alert" class="lumen-boot-error">This experience failed to load. Please reload the page.</p>';`);
        ew.line("this.dispatchEvent(new CustomEvent('lumen:boot-error', { detail: err }));");
      });
    });
    bw.line();
    bw.block(`disconnectedCallback()${ann(ctx, ': void')}`, (cw) => {
      cw.line('this.bootGen++; // invalidate any in-flight boot');
      cw.line('const disposable = this.engine;');
      cw.line('this.engine = null;');
      cw.line('void disposable?.dispose?.();');
    });
    bw.line();
    bw.block(`attributeChangedCallback(name${ann(ctx, ': string')})${ann(ctx, ': void')}`, (cw) => {
      cw.block("if (name === 'config-url' && this.isConnected)", (iw) => {
        iw.line('void this.boot(); // dispose-before-reboot handled inside boot()');
      });
    });
    bw.line();
    bw.block(`async resolveIR()${ann(ctx, ': Promise<typeof SCENE_IR>')}`, (cw) => {
      cw.line("const url = this.getAttribute('config-url');");
      cw.line('if (!url) return SCENE_IR;');
      cw.line('const res = await fetch(url);');
      cw.line('if (!res.ok) throw new Error(`lumen-embed: failed to fetch config ${url}: ${res.status}`);');
      cw.line(`return (await res.json())${ann(ctx, ' as typeof SCENE_IR')};`);
    });
  });
  w.line();
  w.block("if (!customElements.get('lumen-embed'))", (bw) => {
    bw.line("customElements.define('lumen-embed', LumenEmbed);");
  });
  return finalizeModule(b.build(), ctx.options);
}

/** Run the 'webcomponent' target. */
export function generateWebComponent(
  ctx: TargetContext,
): Pick<CodegenResult, 'entry' | 'files' | 'ssrHtml' | 'hydrationManifest'> {
  const mod = renderWebComponent(ctx);
  return {
    entry: mod.path,
    files: [mod],
    ssrHtml: '',
    hydrationManifest: {
      islands: ctx.ir.hydration.islands.map((id) => ({
        id,
        module: mod.path,
        trigger: 'eager' as const,
        props: { sceneId: id, host: 'shadow-dom' },
      })),
    },
  };
}
